### ISSUE TITLE
gain/loss of interaction for different alleles. 

### ISSUE THREAD

**Issue by baoxingsong** [lightdock/lightdock#17]
Hi, @brianjimenez 

I am working on quantitative genetics and would like to investigate the natural variation of PPI.

Do you think lightdock is a good tool to investigate the impact of natural variation (SNP/INDEL) on gain/loss of interaction, please?

**Comment by brianjimenez** [comment]
Adding @JorgeRoel to the discussion

**Comment by JorgeRoel** [comment]
Hi @baoxingsong,

Thanks for your inquiry (and email) and your interest in LightDock.

If I understand correctly, you want to explore the effect of single mutations at protein-protein interfaces? From your email, I read that you'd like to do this for several species and, I assume, for a relatively large amount of proteins. Are these binary complexes? Do you have information about putative interfaces (perhaps evolutionary information)? These are important features in order to select the proper methodology.

I believe LightDock could be useful for generating docking models of large amounts of protein complexes (only binary), since it is easily scalable, fast (specially in its Rust implementation: https://github.com/lightdock/lightdock-rust) and can incorporate information about putative interfaces in the form of residue restraints. Besides correctly predicting PPIs, you may need a scoring function (or delta delta G predictor) sensitive enough to single residue mutations. By default, LightDock uses DFIRE scoring function to discriminate between native/non-native complexes, which has been shown to correlate well with experimental binding energies in the past (https://pubmed.ncbi.nlm.nih.gov/15801826/), but I am not sure whether it may be accurate enough for your purpose (never been tested I believe). 

I leave here this recent publication that may be of your interest: https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008449, in which they used already docked/modelled complexes to assess for mutations in protein-protein interfaces from different species but at the same system.

**Comment by baoxingsong** [comment]
Thanks so much for this informative reply. Yes, I am thinking of binary interactions.

The binary protein-protein interactions identified using high throughput yeast two-hybrid approach for several thousand proteins are publicly available. I plan to predict proteome-wide protein-protein binary interactions. Previous protein-protein binary interaction prediction using a docking approach (the HEX program) generated reasonable results (https://academic.oup.com/plphys/article/179/4/1893/6116834). I am looking for a state-of-the-art docking approach to repeat what they did and extend that with real biological scientific questions.

The PLoS Comput Biol paper you shared is highly related to the question in my mind, and I would like to conduct that interaction score analysis on proteome-wide interactions.
I guess the information on putative interfaces is not available. The protein sequence evolutionary information is available. We generated a matrix that could be used to evaluate the loss of interaction prediction.

**Comment by JorgeRoel** [comment]
Sounds cool! Do not hesitate to contact us back if you finally decide to use LightDock and need any support.
