### ISSUE TITLE
Results and replication Protein–Protein Docking Benchmark 5.0

### ISSUE THREAD

**Issue by knuser** [lightdock/lightdock#26]
Are results from "Protein–Protein Docking Benchmark 5.0" (https://zlab.umassmed.edu/benchmark/) available for LightDock? This benchmark is mentioned in your original paper https://academic.oup.com/bioinformatics/article/34/1/49/4103399?

Or is there any replication scenario/protocol which I could run by myself?

I'm facing not conclusive docking scores using default LightDock parameters and examples from mentioned benchmark.

My setup:
* `lightdock==0.9.2`
* pdb files were taken from Benchmark 5.5
   * receptor names were from `{name}_r_u.pdb.gz` files
   * ligand names were from `{name}_l_u.pdb.gz` files
* executed commands were:
   * `lightdock3_setup.py receptor.pdb ligand.pdb --noxt --noh --now`
   * `lightdock3.py setup.json 100`
   * for fetching results: ```lgd_rank.py `ls -d ./swarm_* | wc -l` 100``` and then first score from `rank_by_scoring.list`

Scores I got for few examples:
```
1CLV	26.133
1FLE	27.331
1GL1	24.781
1OC0	25.235
1PPE	23.721
1R0R	24.928
2ABZ	29.969
3SGQ	24.173
4CPA	25.791
1FCC	37.313
1XU1	26.460
1CGI	25.396
```

Then for exact same receptors I had used ligand from `1GL1` to check what would results be, if I choose "random", non binding example. Scores were:
```
1CLV	27.660
1FLE	25.199

1OC0	22.970
1PPE	25.460
1R0R	22.275
2ABZ	22.084
3SGQ	22.410
4CPA	23.180
1FCC	32.067
1XU1	22.515
1CGI	26.573
```

As you can see scores for non binding examples are very similar as for real ones.

Was I just out of luck and had chosen only examples, which LightDock is unable to check for binding? Can you provide complex  names from benchmark with high LightDock score?
What should be threshold score for cutoff with default LightDock setup? Is it always something around 50? In tutorial https://lightdock.org/tutorials/0.9.2/restraints I got best score around 56-57.

Thank you for your great work

**Comment by JorgeRoel** [comment]
Hi @knuser,

Thanks for your interest in LightDock. Of course, we do have the results of the paper you mention, but not on a public repository due to storage restrictions (thousand of models * 230 cases). You can just send us an email and we'll find a way to send them to you. In the meantime, you can find the results of the newest 55 entries of BM5 from this publication: https://academic.oup.com/bioinformatics/article/36/3/950/5550626 at https://github.com/lightdock/lightdock_bm5 as well as the scripts to generate all the PDB files. Please, bear in mind that version=0.9.2 includes several improvements compared to version=0.7.0 (the version used in the paper I shared with you), so that the numbers might not be identical between versions. If you want to replicate the results, you would need to install the exact same LightDock version.

With regards to scoring, in general, docking scoring functions hardly correlate with binding affinities, so comparing scores between different systems as you did (A-B vs A-C) by using docking is usually not a good idea. There are other tools (e.g. binding affinity predictors) out there better suited for this task. 

And the answer to your last question is no, scores will vary between systems, and again, in general one might expect lower (or higher as in our case) scores for larger interfaces so that, comparing between different systems or setting absolute thresholds might be inappropriate. 

Cheers.
