### ISSUE TITLE
LightDock setup failure - Found wrong coefficient on calculating poses with restraints

### ISSUE THREAD

**Issue by kaze33** [lightdock/lightdock#4]
Greetings, 

I've been running LightDock successfully with my files but there is a ligand that fails to work whenever I define restraints. I did not change anything else but the ligand PDB file and the restraints file content, yet i get the following errors at the end of lightdock3_setup.py:

INFO: Calculating starting positions...
ERROR: LightDock setup failed. Please see:
ERROR: [LightDockWarning] Found wrong coefficient on calculating poses with restraints

I fail to detect the problem and I tried everything from shortening the PDB ligand structure, redoing the restraints file, running less swarms or steps, deactivating flexibility... Only removing the restraints fixes it, obviously. 

Here I provide a zip file with the receptor (HER2noH) and ligand (EM1noH) PDB files with H removed, the restraints file, and the .sh script I call using "bash". I am working using Ubuntu in WSL2 environment from Windows 10. As I said, I have been successful in using restraints with other ligands and receptors using the same environment and script.

Could you help shed some light onto this issue? Maybe some specific way to figure out where the error appears exactly? Many thanks.

Best,
Eloi Parladé.

[support.zip](https://github.com/lightdock/lightdock/files/4797895/support.zip)

**Comment by brianjimenez** [comment]
Hi Eloi,
Thank you for using LightDock. We had a quick look to the issue. The raised error `Found wrong coefficient on calculating poses with restraints` is a safety check for degenerate corner cases when trying to preorient ligand poses against simulated *dummy* residues over the receptor surface. Depending on the ligand shape and the initial ligand translation within the swarm, some preorienting might not be possible. To avoid this situation, the simplest solution is to swap receptor and ligand. Indeed, we think that has some advantages in this scenario as many less swarms are going to be generated and thus simulation time will be decreased.

Please follow these instructions to make this simulation setup working:

1. Remove all `HETATM` from both PDB structures.
2. Swap L -> R in restraints file:
 ```
R A.GLY.27
R A.ALA.28
R A.THR.29
R A.SER.30
R A.ASN.31
R A.ILE.32
R A.SER.33
R A.SER.53
R A.ARG.54
R A.ALA.55
R A.GLU.56
R A.SER.57
R A.ARG.58
R A.PRO.59
R A.PRO.102
R A.LEU.103
R A.VAL.104
R A.ARG.105
R A.HIS.106
R A.LYS.107
 ```
3. Re-run the setup:
 ```
lightdock3_setup.py EM1noH.pdb HER2noH.pdb 400 200 -anm --noxt --noh -rst restraintsEM1.list
 ```

Setup now completes successfully: 

![complex](https://user-images.githubusercontent.com/4330278/85037382-96fab180-b185-11ea-9ad8-eef2e30ceddf.png)

(with the bonus of only simulating 56 swarms instead of 400!). This protocol of using only restraints in the ligand side was developed for our new research using explicit membrane representation which will be available very soon.

**Comment by kaze33** [comment]
Thanks a lot for the clarification and the steps to solve the issue, it worked perfectly when I switched ligand and receptor!

Best,
Eloi
