### ISSUE TITLE
lightdock pdb file visualises incorrectly in pymol

### ISSUE THREAD

**Issue by Jorisvansteenbrugge** [lightdock/lightdock#46]
**Describe the bug**
I ran lightdock on two proteins following the simple docking tutorial (https://lightdock.org/tutorials/0.9.3/simple_docking. All the steps ran successfully, but when I open de best scoring PDB file (or any for that matter) it does not show like a molecule (see screenshots below).

**Expected behavior**
I expect a docked visualization of the two proteins, like in the tutorial

**Screenshots**
![example](https://user-images.githubusercontent.com/7196110/218771983-64cd4bc3-6439-4338-b839-ac4362280f74.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04.5 LTS 
 - lightdock version 0.9.3

**Comment by brianjimenez** [comment]
This is probably caused by 1) same chains on receptor or ligand or 2) no chain Ids assigned in the input PDB structures. Please note this is a problem with PyMol software, if you open the predicted structures with a different software (ChimeraX, etc.) you won't probably experience this issue. Please, could you check @Jorisvansteenbrugge ?

**Comment by JorgeRoel** [comment]
My bet is on 1), both have chainID A (they look like AlphaFold predictions)

**Comment by alchemistcai** [comment]
I used to meet similar problem.The proteins may have same chain names,say chain A,which confuses pymol the connection table of proteins.Use  pymol's `alter chain A,chain='B'` command to alter one of the chain name.

That's why in official tutorials,the receptor's chain is R and the ligand's chain is L.

**Comment by Jorisvansteenbrugge** [comment]
@brianjimenez Thanks for the reply. It was indeed option 1), like @JorgeRoel and @alchemistcai mentioned. After renaming the chains everything worked as expected. Thank you.
