### ISSUE TITLE
 ERROR: [NormalModesCalculationError] Number of atoms is different

### ISSUE THREAD

**Issue by lonngxiang** [lightdock/lightdock#47]
![image](https://user-images.githubusercontent.com/40717349/220562165-b03f7922-d276-4b93-9e08-27d8142ac97f.png)
repair protein backbone or sidechain atoms, and still report errors

**Comment by zhl10154** [comment]
same here, remove _-anm_ could fix it, but don't know the impact

**Comment by lonngxiang** [comment]
> 

but I want  flexible docking，Is there any way to solve it？

**Comment by JorgeRoel** [comment]
@zhl10154 , could you please share your PDB files with me? jrg.roel@gmail.com

**Comment by brianjimenez** [comment]
This problem is caused by ProDy not recognizing partial residues and the error is raised to avoid inconsistencies in the atom numbering when ANM is applied (backbone flexibility). Thanks @JorgeRoel for providing support by email. In the meantime, I recommend to use [pdbfixer](https://github.com/openmm/pdbfixer) with input structures, since that is an excellent software to rebuild missing atoms.

**Comment by zhl10154** [comment]
> @zhl10154 , could you please share your PDB files with me? [jrg.roel@gmail.com](mailto:jrg.roel@gmail.com)

Thanks for help, @JorgeRoel . I have sent pdb files to your email.

**Comment by zhl10154** [comment]
@lonngxiang problem solved by using pdbfixer. Install it and use command `pdbfixer xxx.pdb` to reconstruct protein file, and run lightdock again.

Thanks for your kindly help and support @brianjimenez @JorgeRoel
