### ISSUE TITLE
Question about the treatment of protein-ligand docking.

### ISSUE THREAD

**Issue by xavgit** [lightdock/lightdock#61]
Hi,
it is possible to use lightdock for ligand-receptor docking when in the active site 
or docking box are present metal bivalent ions such as MGs or CAs?

In the case of my interest I have two Mgs ions in the active site.

Thanks.

Saverio

**Comment by brianjimenez** [comment]
Hi @xavgit, LightDock is not intended for protein-ligand docking (despite it can be hacked to perform it, but with the limitation of the ligand being rigid since torsion angles are not supported). I advice to use specifically-designed software for that purpose.

**Comment by alchemistcai** [comment]
![Screenshot_20231006_221358](https://github.com/lightdock/lightdock/assets/60164864/eb24a494-3fa8-4e3a-9ade-85f473dfa1c1)

In short,I think lightdock can generate appropriate poses according to MGs' restraints(maybe CA later) in theory,but the implementations need to be modified.

Right now,lightdock can parse `MG` as a valid atom,but the default `dfire` scoring function does not calculate vdw/elec contributions of metals as `dfire` mainly focus on protein-protein docking.

Other implemented scoring function like `cpydock,dna,vdw,sd` contains parameters of MG,but they need to be adjusted a little as they also have the same problem above.Their amber atom_types and/or charges need to add MG and other non-standard residues.

However,the restraints can still keep ligands around MG because of the restraints weight penalty and post-filters.MG can contribute to the scoring function and the final pose in a different and less precise way,with the absence of MG's vdw/elec contributions.The difference is similar with that between geometric matching and energy matching,but not that big for just a few metal ions.

P.S.

1. CA needs to edit input pdb files as CA's atom name listed as `C0` to avoid confusion with alpha-C.Lightdock also needs to be adjusted more.
2. When you say `ligand`,you mean peptides or nucleic acid  fragments,right?Lightdock only recognizes protein and nucleic acid residues and a part of atoms.It's not designed for small molecules ligands.

**Comment by xavgit** [comment]
Ok.
Thanks for this detailed answer.

Saverio
