### ISSUE TITLE
public server output pdb is renumbered

### ISSUE THREAD

**Issue by bifxcore** [lightdock/lightdock#74]
**Describe the bug**
My input target contains multiple deletions. When I download the PDB file, all the residues have been renumbered, which makes it super hard to select residues to do downstream analysis.

**To Reproduce**
delete a few loops from the input target pdb file, do the docking, get back pdb file of complex. Input target pdb file residues have been renumbered.

**Expected behavior**
Target residue numbers have biological meaning and should be preserved.

**Screenshots**
NA.

**Desktop (please complete the following information):**
website https://server.lightdock.org/

**Additional context**
NA

**Comment by JorgeRoel** [comment]
Hi @bifxcore

This phenomenon is due to the minimization step after LightDock as openmm automatically renumbers the PDB files. If you inspect top11 model and below you will no longer see it. I advise you to disable minimization to avoid renumbering and perform a relaxation of the topX lightdock models with any protocol of your choice (to declash the interfaces)

**Comment by brianjimenez** [comment]
@bifxcore when you download the results from the LightDock server (a tar gzip file), in the `top/` folder you will find the minimized top structures by OpenMM (`min_*.pdb`), the previous fixed structures by `pdbfixer` (`fixed_*.pdb`) and the regular top structures generated by LightDock (`top_*.pdb`). The last ones follow the same numbering as provied as input to LightDock.
