### ISSUE TITLE
lgd_move_anm.py script

### ISSUE THREAD

**Issue by stianale** [lightdock/lightdock#75]
Hi, I am having troubles using the script lgd_move_anm.py for generating normal modes for my protein and DNAs. Firstly, it does not seem to be an all-atom normal mode analysis, which I need. Secondly, using large rmsd values, I get an error that the distances between residues in my output strutures are too large.

**Comment by brianjimenez** [comment]
Hi @stianale , that script is a basic stub for conformational sampling in LightDock provided the ANM model calculated by the ProDy library. I suggest reading and to follow their official tutorial [here](http://prody.csb.pitt.edu/tutorials/conformational_sampling/) to be able to write your own normal mode analysis module.
About your second comment, large RMSD values would probably break the internal geometry of the molecule, which is a known limitation of ANM.
Feel free to reopen this issue if you feel there is something else concerning LightDock.

**Comment by stianale** [comment]
I am wondering about ProDy. If using the -anm flag, how many states for each of the lowest normal modes is being crossdocked? I know how to do all-atom normal mode analysis in bio3d in R, but not ProDy. I have done many dockings where I saved trajectories from the lowest-frequency normal modes of my protein and DNA from bio3d, extracted for each normal mode two very flexible states, added hydrogens (using reduce) and crossdocked the models. This is of course computationally very expensive and slow, but I can't see that using the in-built -anm flag would be as accurate as the approach I just mentioned?

Thanks for the link, by the way, I will look into it.

**Comment by brianjimenez** [comment]
To answer your first question @stianale, LightDock includes the first non-trivial normal modes for receptor and ligand (10 by default, but configurable by the user with `ar` and `al` flags) in the optimization vector for every glowworm. That means that there is no cross-docking _per se_, but optimization in the ANM space.
I think your approach makes totally sense since you're selecting the most representative flexible states of the molecules. You may enable `-anm` on them, but maybe I'd limit the ANM fluctuations by RMSD with `--anm_rec_rmsd` and `anm_lig_rmsd`.
