### ISSUE TITLE
Membrane vs Transmembrane

### ISSUE THREAD

**Issue by alexandrefassio** [lightdock/lightdock#77]
Hi,

I don't know if this is a bug or an expected behavior. I have a transmembrane protein that has, therefore, domains above and below the membrane. I'm trying to dock a ligand specifically against the lower part of that protein. 

However, when I run the setup using --membrane as shown in the tutorial, swarms would cover only the "upper" part of the protein. I debugged the code and found out this happens because of this line:

https://github.com/lightdock/lightdock/blob/4654ee58542e99174776b2f80dbcfb673e918da1/lightdock/prep/poses.py#L435

On the other hand, if I use the flag --transmembrane, only the region between the layers is selected, which happens due to the following lines:

https://github.com/lightdock/lightdock/blob/4654ee58542e99174776b2f80dbcfb673e918da1/lightdock/prep/poses.py#L427-L433

So, I wonder if either the flag --membrane or --transmembrane should not return the upper and lower protein region.

To achieve this, I modified the transmembrane block as follows:

<pre>
if is_transmembrane:
        upper = upper_layer(layers)
        bottom = bottom_layer(layers)
        max_z = min(upper) + translation[2]
        min_z = max(bottom) + translation[2]
        for swarm_id, center in enumerate(swarm_centers):
            # if center[2] >= min_z and center[2] <= max_z:
            <b>if center[2] < min_z or center[2] > max_z:</b>
                compatible.append(center)
</pre>

bests

**Comment by JorgeRoel** [comment]
Hi @alexandrefassio 

Thanks for your query. This is indeed the expected behaviour in LightDock. While --transmembrane was meant to sample transmembrane regions i.e. those between upper and lower regions and therefore model dimerization processes (not systematically tested though), --membrane was conceived to model membrane protein-soluble interactions (either extracellular or cytosolic). The generation of the swarms is driven by the orientation of the input system (protein + membrane) in LightDock. If you want to sample "lower" regions, you would only need to apply a 180º transformation across your desired axis.

To sample both regions, you might need to either perform to independent runs or perform two different setups and then combined the files in a appropriate manner (avoiding duplicates in file names) and possibly manually modifying the setup.json.
